# Generated by Django 2.1.7 on 2019-03-25 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.FloatField()),
                ('lent', models.FloatField()),
                ('date', models.DateField(verbose_name=datetime.datetime(2019, 3, 25, 9, 15, 29, 130218, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('GroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ShareBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.FloatField()),
                ('GroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
                ('PersonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.GroupMembers')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Expense')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='GroupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.ExpenseCategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paidby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.GroupMembers'),
        ),
    ]
