# Generated by Django 2.1.7 on 2019-03-24 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 3, 24, 2, 54, 1, 133166, tzinfo=utc)),
        ),
    ]
