# Generated by Django 2.1.7 on 2019-03-26 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20190326_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='email_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Groups.Register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 3, 26, 11, 16, 41, 768641, tzinfo=utc)),
        ),
    ]
