# Generated by Django 2.1.7 on 2019-03-24 03:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_auto_20190324_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 3, 24, 3, 23, 48, 797072, tzinfo=utc)),
        ),
    ]
