# Generated by Django 2.1.7 on 2019-03-24 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0005_auto_20190324_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='GroupId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Groups.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 3, 24, 4, 48, 41, 94298, tzinfo=utc)),
        ),
    ]
