# Generated by Django 2.1.7 on 2019-03-24 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0006_auto_20190324_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='lent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 3, 24, 11, 27, 19, 624348, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='sharebill',
            name='GroupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group'),
        ),
        migrations.AddField(
            model_name='sharebill',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.GroupMembers'),
        ),
        migrations.AddField(
            model_name='sharebill',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Expense'),
        ),
    ]
