# Generated by Django 2.1.7 on 2019-03-24 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0007_auto_20190324_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 3, 24, 11, 32, 53, 550126, tzinfo=utc)),
        ),
    ]
